### ISSUE TITLE
[Proj Planning] Existing Tasks in To Dos 

### ISSUE THREAD

**Issue by tonyxj** [psybuzz/goldenconversations#37]
Hi Guys, 

We added four new tasks to the To Dos bucket in Trello, based on our great discussion on Friday, which are, transferring domain, changing passwords, testing the app, transfer domain.

What about the rest of the tasks from before? (Highlighted in red box in the image below.)
Should we plan to work on them? @nikilselvam @psybuzz 

![image](https://cloud.githubusercontent.com/assets/6765882/5607674/e868b6ba-9418-11e4-98fe-2deca2285603.png)

**Comment by psybuzz** [comment]
Hmm, it seems like these red-highlighted tasks have been there for awhile.  Since we have a release plan for early January on the newer tasks, I think that we could probably push the red-highlighted ones until after we finish the share of newer tasks, or if we have free time.

Looking at a glance, if I were to rate the red-tasks on a Fibonacci scale, I would probably give most 2's or 3's, except for "Turning on/off Email Notifications", which looks like much more work.  Since it likely involves a per-user setting/changing the schema, I'd set that at a 5.  So I think that one should definitely be put off until later.

**Comment by tonyxj** [comment]
I think that's a good way to approach it!. Let me move those tasks into the archive bucket first. If and when we have free time after we finish the four major tasks, we pick off these, one by one from the list. What do you think @nikilselvam ?

**Comment by nikilselvam** [comment]
Yeah, this sounds good to me. The one that I think might be nice to have done is creating a new email account to send out notifications. If we can get this one done, we can make sure that the email notifications work when we're testing the system as a whole. What do you guys think?

**Comment by psybuzz** [comment]
I agree, the new email-er for notifications sounds like a key change, so it would be nice to get that in before testing.

**Comment by tonyxj** [comment]
Moved the tasks in place. Closing.
