### ISSUE TITLE
[Proj Planning][Feature] Forget Password + Settings

### ISSUE THREAD

**Issue by tonyxj** [psybuzz/goldenconversations#38]
Guys, one feature that is in neither Icebox nor To Dos is Forget Password.

This feature will require several new UI screens (assuming we're prompting users to type in email: input email modal, email link sent, email not found, and a page to create new password after retrieving link).

It will also require quite a bit of back-end work: 1st, generating and sending the customized link that the user can access to change the password. 2nd, the feature of changing the password and other work I've not accounted for here. 

A related functionality is a settings area for users to change their password, (and possibility name?) inside the app, without having to log out and go through the forget password flow.

Given these circumstances, do you guys think @psybuzz @nikilselvam 
A. Is forget password a must have for a web app like this? (I'm leaning towards a yes, as I think it's an integral piece of any public facing app, similar to the issue of password encryption, but I want to hear your guys' opinions.)
B. If we're pursuing building this, what are the time estimates?
C. If we decide to forgo building this, what options do we have / what can we do to make the user experience is good?

**Comment by nikilselvam** [comment]
I would say:

A. I think that a forget password feature is a necessity. It would be nice to have it for our first release, but it's also okay to not have it in my opinion since this is a beta release. 

B. It would take a few weeks of concentrated work to get this done. There are quite a few frontend and backend requirements, so perhaps we can divide this task up and work on it concurrently

C. We could put in a note to have users email us if they forgot their passwords (or perhaps have a button that sends us a notification that a user has forgotten their password). We could then either reset their password to a random string and send them an email manually (although this doesn't feel too secure). This seems to be one of the quickest solutions, although I don't think that it's a very convenient one

**Comment by psybuzz** [comment]
A. I agree with you and Nikil.  This is probably best left for a later date.

B. I agree with Nikil's time estimate.  However, for work to begin on the backend, I think we'd have to make some decisions about security, such as:
- Should we force users to enter a security question if they want to reset/change password?
- If so, should users have a security question when they create their account?  If so, then all beta users won't have this option... :(
- Can a user change their email address?

C. For the near future, Nikil's suggestion is likely the best we can do.  Since we might still have to address questions in B., it might be better to put implementing "Change Password" from inside the app at a higher priority than "Forget Password".  If we manually change a user's password to a random string, they can at least change it back to what they want using "Change Password".

**Comment by tonyxj** [comment]
Great questions.
I think for the complete app, users should be allowed to change password and / or email.
But I don't think security questions are necessary. The rationale is that security questions are in general hard to remember and not useful, so nowadays, apps, by and large, rely on users' email and in some cases phone numbers for security.

For the immediate future, I think we should aim to build a change password feature in the app, this way we can knock off two features with one functionality. With this feature in place, we can change the "forgot password" button to a password reset request modal, where the user, when logged out, can confirm whether she/he would us to set a temporary password, to be sent to the said email address. Upon receiving the new temp password, the user can simply login and change the password him/herself.

**Comment by tonyxj** [comment]
Changes in PR. 

Closing.
