### ISSUE TITLE
Email verification

### ISSUE THREAD

**Issue by psybuzz** [psybuzz/goldenconversations#44]
Hey guys, I came across another question while working on the forgot/change password feature.  When a user first signs up for GC, we currently have no way of verifying whether the email that they provide is actually theirs or not.

Right now, we are assuming that each user will sign up with his or her email, but let's say, one day, we have lots and lots of users.  Someone malicious might make an account with the username "eton.nusk@gmail.com", knowing that it's the real email of "Eton Nusk", who may be a celebrity.  The malicious person might be able to deny famous people from signing up for our service!

I'd like to propose email verification on user signup as another priority.  The implementation might have some similarities with the password reset feature I'm working on, if both end up using a token based method.  What do you guys think, @nikilselvam @tonyxj ?

**Comment by tonyxj** [comment]
I think this is a very valid point @psybuzz. As fully functioning app, this would an expected feature. 
I agree to add it the list of priority tasks.

I think this task entails four things:
1. Sending users an email with a link to verify their account
2. (The users click on the link), those coming from their email
3. A handshake at the back verifies that they're indeed coming from the right address
4. Their account gets created

Does this sounds right? @psybuzz @nikilselvam

**Comment by nikilselvam** [comment]
I think that's a great idea, Erik. Yup, those look like the steps that I would include as well, Tony.

When you think about it, we should have all of the standard features that most sign-up services have (email verification, password reset, delete account, etc.). I think that we should add this one and then also look at implementing delete account functionality at some point. It doesn't have to be for the beta release necessarily, but I think that's it's a good one to have prior to the release f possible.

I feel okay pushing back our beta release by a week or two if it means getting these features in. It'll be much easier to complete them now and make sure everything works like we'd want it to rather than making changes later on after we have actual users in the system. What do you guys think?

**Comment by tonyxj** [comment]
I agree, rather be safe than sorry when dealing other people's personal information and expectations . Let's get to the MVP. I'm favour of pushing back the release date till the features are in place. I agree, the delete account feature can be stretch goal.

**Comment by psybuzz** [comment]
Dang!  You guys respond quickly!

@nikilselvam, yeah, they do seem like pretty standard features, I agree we should have them earlier the better.  In terms of technical work, the steps outlined by @tonyxj are pretty much it, except I think we'd also have to defer the creation of the actual user in the database until later.

Email verification and Password reset would be similar, in fact, the first 3 tasks:
1. Sending user an email with a link to verify their account
2. (The users clicks on the link), the one coming from their email
3. A handshake at the back verifies that they're indeed coming from the right address

would probably be exactly the same, except for the contents of the email.  Since they both share a lot of the code, I'd be willing to take on Email Verification once I finish Password Reset.  I believe that we could still get these features in on schedule!

Right, delete account sounds like a good stretch goal, something that could probably be done after the beta.

**Comment by tonyxj** [comment]
Sounds good. Task is documented in Trello as [Add email verification to new account creation].

Closing.
