### ISSUE TITLE
Writing down initial thoughts when creating a conversation may not work

### ISSUE THREAD

**Issue by nikilselvam** [psybuzz/goldenconversations#46]
Guys, I was playing around with conversation creation. When a user creates a conversation, they are allowed to choose a question, the people to participate in the conversation, and their initial thoughts.

![screen shot 2015-01-13 at 1 03 23 pm](https://cloud.githubusercontent.com/assets/5490475/5728060/b5eb4168-9b24-11e4-8412-1ae454e0bfad.png)

I typed into the Initial Thoughts section, but it did not save my text as the first post in the conversation as expected. Have you guys run into this problem too? This is something that we may want to add if it hasn't been implemented yet.

**Comment by psybuzz** [comment]
Yeah, this is something that we haven't implemented yet.  If beta users see it, type, and we simply drop/ignore their thoughts, that could be disastrous.

I do think that some other tasks related to design and security have a high priority, but this bug is something that "blocks" or hampers the user experience in some way, that could make people potentially angry.  This feature doesn't seem overly complicated, and if we could implement this feature by the deadline, that would be great.  If we do not make it, I suggest that we simply hide the field until it gets implemented.  I can definitely add it into the Trello, for now.

How about you @tonyxj ?

**Comment by tonyxj** [comment]
I agree. Let's make it a stretch goal! We can also always remove it from the design if we don't get to it in time.

**Comment by tonyxj** [comment]
In Trello. Closing.
